[package]
name = "flat_spatial"
version = "0.1.0"
authors = ["Douady Pâris <paris.douady@hotmail.fr>"]
edition = "2018"
keywords = ["algorithms", "spatial", "geometry", "grid", "data-structures"]
description = "Flat spatial partitionning algorithms and data structures"
license-file = "LICENSE"
readme = "README.md"
categories = ["algorithms", "graphics", "data-structures", "game-engines"]
exclude = ["img/*"]

[dependencies]
slotmap = {version = "0.4", default-features = false}
mint = "0.5.5"

[dev-dependencies]
criterion = "0.3"
rstar = "0.8.0"
rand = "0.7.3"

[[bench]]
name = "storage_bench"
harness = false